import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "@/assets/globals.css";
import DataProvider from "./providers/DataProvider";

export const metadata: Metadata = {
  title: "Ethereum Gas Tracker",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <DataProvider>{props.children}</DataProvider>
      </body>
    </html>
  );
}
